server.port=8080
server.error.include-message=always
server.error.include-binding-errors=always

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.search.backend.type=elasticsearch
spring.jpa.properties.hibernate.search.backend.protocol=http
spring.jpa.properties.hibernate.search.backend.hosts=${HIBERNATE_SEARCH_BACKEND_HOSTS:elasticsearch:9200}
spring.jpa.properties.hibernate.search.schema_management.strategy=create-or-update
spring.jpa.properties.hibernate.search.indexing.plan.synchronization.strategy=sync
spring.jpa.properties.hibernate.search.automatic_indexing.enabled=true

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
springdoc.packages-to-scan=fr.fullstack.shopapp.controller

logging.level.root=INFO
logging.level.fr.fullstack.shopapp=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.search=INFO
